### ISSUE TITLE
I cant find Browser.db file

### ISSUE THREAD

**Issue by musky603** [Badprt23/Android-Firefox-Bookmarks#1]
Maybe main mozilla android browser contains browser.db file inside data/user folder of android file system but in most cases if you are using another android product of mozilla firefox like for example: firefox for developers, focus or maybe the latest version of all the mozilla products including your browser, then there is a high chance that it contains **places.sqlite** file instead of browser.db which is having totally different tables inside of it. 
I dig deep for almost 8 hours to find the file then the correct table and result is **places.sqlite** file for which you need to run that bookmark.sql command for the table called **moz_places** present inside with some changes in query for example I write Select id, title, url query inside bookmark.sql file, then only you get the result what you want 👍 
Thanks to your tutorial & firefox forums otherwise I would have cried in depression 🤣
 sorry for long letter I am noob in english I cant explain in 2-3 line

**Comment by Badprt23** [comment]
Tested and New Branch created

**Comment by musky603** [comment]
Thank you so much for accepting my changes & sorry again for bad typos actually I was totally blank that time due to 8 hours of firefox bookmarks research but due to the risk of less information available on internet for this file, I make up my mind to at least provide info as soon as possible
